openapi: 3.2.0
info:
  title: Skyvia public Account API
  version: v1
security:
- Access Token: []
tags:
- name: Account
paths:
  /v1/account/users:
    get:
      tags:
      - Account
      summary: Get account users
      parameters:
      - name: searchMask
        in: query
        description: search by user name
        schema:
          type: string
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountUserDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/AccountUserDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/AccountUserDtoHasMorePagingDto'
      operationId: getV1AccountUsers
      x-operation-id-source: derived
    delete:
      tags:
      - Account
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/RemoveAccountUserRequestDto'
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveAccountUserRequestDto'
          text/json:
            schema:
              $ref: '#/components/schemas/RemoveAccountUserRequestDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RemoveAccountUserRequestDto'
      responses:
        '200':
          description: OK
      summary: Delete account users
      x-summary-source: derived
      operationId: deleteV1AccountUsers
      x-operation-id-source: derived
  /v1/account/invitations:
    get:
      tags:
      - Account
      summary: Get account invitations
      parameters:
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountInvitedUserDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInvitedUserDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/AccountInvitedUserDtoHasMorePagingDto'
      operationId: getV1AccountInvitations
      x-operation-id-source: derived
    post:
      tags:
      - Account
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/InviteUserRequestDto'
          application/json:
            schema:
              $ref: '#/components/schemas/InviteUserRequestDto'
          text/json:
            schema:
              $ref: '#/components/schemas/InviteUserRequestDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/InviteUserRequestDto'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
            application/json:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
            text/json:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
      summary: Create account invitations
      x-summary-source: derived
      operationId: postV1AccountInvitations
      x-operation-id-source: derived
  /v1/account/invitations/{invitationId}/resend:
    post:
      tags:
      - Account
      parameters:
      - name: invitationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
            application/json:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
            text/json:
              schema:
                $ref: '#/components/schemas/InvitedUserStatusDto'
      summary: Create account invitations by invitation id resend
      x-summary-source: derived
      operationId: postV1AccountInvitationsByInvitationIdResend
      x-operation-id-source: derived
  /v1/account/invitations/{invitationId}:
    delete:
      tags:
      - Account
      parameters:
      - name: invitationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
      summary: Delete account invitations by invitation id
      x-summary-source: derived
      operationId: deleteV1AccountInvitationsByInvitationId
      x-operation-id-source: derived
components:
  schemas:
    AccountWorkspaceUserDto:
      type: object
      properties:
        workspaceId:
          type: integer
          format: int32
        roleName:
          type:
          - string
          - 'null'
        roleId:
          type: integer
          format: int32
      additionalProperties: false
    InviteUserRequestDto:
      required:
      - email
      - userType
      type: object
      properties:
        email:
          minLength: 1
          type: string
          example: johnDou@email.org
        userType:
          enum:
          - Administrator
          - Member
          type: string
          example: Member
        workspaces:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/InviteToWorkspaceDto'
      additionalProperties: false
    AccountUserDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AccountUserDto'
        hasMore:
          type: boolean
      additionalProperties: false
    AccountInvitedUserDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AccountInvitedUserDto'
        hasMore:
          type: boolean
      additionalProperties: false
    RemoveAccountUserRequestDto:
      type: object
      properties:
        email:
          type:
          - string
          - 'null'
      additionalProperties: false
    AccountUserDto:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        email:
          type:
          - string
          - 'null'
        fullName:
          type:
          - string
          - 'null'
        type:
          enum:
          - Administrator
          - Member
          type: string
        workspaces:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AccountWorkspaceUserDto'
      additionalProperties: false
    AccountInvitedUserDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type:
          - string
          - 'null'
        type:
          enum:
          - Administrator
          - Member
          type: string
        workspaces:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AccountWorkspaceUserDto'
        invitationDate:
          type: string
          format: date-time
        userId:
          type:
          - integer
          - 'null'
          format: int32
        fullName:
          type:
          - string
          - 'null'
      additionalProperties: false
    InviteToWorkspaceDto:
      required:
      - roleId
      - workspaceId
      type: object
      properties:
        workspaceId:
          type: integer
          format: int32
          example: 123
        roleId:
          type: integer
          format: int32
          example: 3
      additionalProperties: false
    InvitedUserStatusDto:
      type: object
      properties:
        email:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        invitationId:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    Access_Token:
      type: apiKey
      description: Authorization header with the Skyvia access token.
      name: Authorization
      in: header
