openapi: 3.2.0
info:
  title: Skyvia public Integrations API
  version: v1
security:
- Access Token: []
tags:
- name: Integrations
paths:
  /v1/workspaces/{workspaceId}/integrations:
    get:
      tags:
      - Integrations
      summary: Get integrations
      parameters:
      - name: workspaceId
        in: path
        description: Workspace Id
        required: true
        schema:
          type: integer
          format: int32
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdIntegrations
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}:
    get:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationDto'
      summary: Get workspaces by workspace id integrations by integration id
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdIntegrationsByIntegrationId
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/executions:
    get:
      tags:
      - Integrations
      summary: Get finished executions
      parameters:
      - name: workspaceId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: startDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: failed
        in: query
        description: ''
        schema:
          type: boolean
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      - name: sortOrder
        in: query
        description: 'To sort the available list of records in either ascending or descending order. Possible values: asc - ascending order, desc - descending order.The default value is ''asc''.'
        schema:
          type: string
          default: asc
      - name: sortBy
        in: query
        description: 'To sort the records based on the fields: startDate, runId. The default value is ''startDate'''
        schema:
          type: string
          default: startDate
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutions
      x-operation-id-source: derived
    post:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
      summary: Create workspaces by workspace id integrations by integration id executions
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutions
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/executions/{executionId}:
    get:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: executionId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionResultDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionResultDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionResultDto'
      summary: Get workspaces by workspace id integrations by integration id executions by…
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutionsByExecutionId
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/executions/active:
    get:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationExecutionLogDto'
      summary: Get workspaces by workspace id integrations by integration id executions active
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutionsActive
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/executions/cancel:
    post:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
      summary: Create workspaces by workspace id integrations by integration id executions…
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutionsCancel
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/executions/kill:
    post:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
      summary: Create workspaces by workspace id integrations by integration id executions kill
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdExecutionsKill
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/schedule:
    get:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
      summary: Get workspaces by workspace id integrations by integration id schedule
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdSchedule
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/schedule/enable:
    post:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
      summary: Create workspaces by workspace id integrations by integration id schedule enable
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdScheduleEnable
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/integrations/{integrationId}/schedule/disable:
    post:
      tags:
      - Integrations
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: integrationId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/IntegrationScheduleDto'
      summary: Create workspaces by workspace id integrations by integration id schedule…
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdIntegrationsByIntegrationIdScheduleDisable
      x-operation-id-source: derived
components:
  schemas:
    IntegrationExecutionLogDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IntegrationExecutionLogDto'
        hasMore:
          type: boolean
      additionalProperties: false
    IntegrationExecutionLogDto:
      type: object
      properties:
        runId:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
        duration:
          type: integer
          format: int32
        state:
          enum:
          - New
          - Queued
          - Running
          - Succeeded
          - Failed
          - Canceling
          - Canceled
          type: string
        successRows:
          type: integer
          format: int32
        errorRows:
          type: integer
          format: int32
      additionalProperties: false
    IntegrationDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
          description: 'Possible values: dataflow, export, controlflow, replication, import, sync, custom'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        scheduled:
          type: boolean
      additionalProperties: false
    IntegrationDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/IntegrationDto'
        hasMore:
          type: boolean
      additionalProperties: false
    IntegrationScheduleDto:
      type: object
      properties:
        active:
          type: boolean
      additionalProperties: false
    IntegrationExecutionResultDto:
      type: object
      properties:
        runId:
          type: integer
          format: int32
        queueTime:
          type: string
          format: date-time
        startTime:
          type:
          - string
          - 'null'
          format: date-time
        endTime:
          type:
          - string
          - 'null'
          format: date-time
        state:
          enum:
          - New
          - Queued
          - Running
          - Succeeded
          - Failed
          - Canceling
          - Canceled
          type: string
        result:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Access_Token:
      type: apiKey
      description: Authorization header with the Skyvia access token.
      name: Authorization
      in: header
