openapi: 3.2.0
info:
  title: Skyvia public Backups API
  version: v1
security:
- Access Token: []
tags:
- name: Backups
paths:
  /v1/workspaces/{workspaceId}/backups:
    get:
      tags:
      - Backups
      summary: Get backups
      parameters:
      - name: workspaceId
        in: path
        description: Workspace Id
        required: true
        schema:
          type: integer
          format: int32
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdBackups
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}:
    get:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupDto'
      summary: Get workspaces by workspace id backups by backup id
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdBackupsByBackupId
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/snapshots:
    get:
      tags:
      - Backups
      summary: Get finished snapshots
      parameters:
      - name: workspaceId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: startDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: failed
        in: query
        description: ''
        schema:
          type: boolean
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      - name: sortOrder
        in: query
        description: 'To sort the available list of records in either ascending or descending order. Possible values: asc - ascending order, desc - descending order.The default value is ''asc''.'
        schema:
          type: string
          default: asc
      - name: sortBy
        in: query
        description: 'To sort the records based on the fields: startTime, snapshotId. The default value is ''startTime'''
        schema:
          type: string
          default: startTime
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdBackupsByBackupIdSnapshots
      x-operation-id-source: derived
    post:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
      summary: Create workspaces by workspace id backups by backup id snapshots
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdBackupsByBackupIdSnapshots
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/snapshots/{snapshotId}:
    get:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: snapshotId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDetailsDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDetailsDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupSnapshotLogDetailsDto'
      summary: Get workspaces by workspace id backups by backup id snapshots by snapshot id
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdBackupsByBackupIdSnapshotsBySnapshotId
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/snapshots/active:
    get:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupActiveRunDto'
      summary: Get workspaces by workspace id backups by backup id snapshots active
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdBackupsByBackupIdSnapshotsActive
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/schedule:
    get:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
      summary: Get workspaces by workspace id backups by backup id schedule
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdBackupsByBackupIdSchedule
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/schedule/enable:
    post:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
      summary: Create workspaces by workspace id backups by backup id schedule enable
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdBackupsByBackupIdScheduleEnable
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/backups/{backupId}/schedule/disable:
    post:
      tags:
      - Backups
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: backupId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
            text/json:
              schema:
                $ref: '#/components/schemas/BackupScheduleDto'
      summary: Create workspaces by workspace id backups by backup id schedule disable
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdBackupsByBackupIdScheduleDisable
      x-operation-id-source: derived
components:
  schemas:
    BackupDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/BackupDto'
        hasMore:
          type: boolean
      additionalProperties: false
    BackupSnapshotLogDto:
      type: object
      properties:
        snapshotId:
          type: integer
          format: int32
        queueTime:
          type:
          - string
          - 'null'
          format: date-time
        startTime:
          type:
          - string
          - 'null'
          format: date-time
        endTime:
          type:
          - string
          - 'null'
          format: date-time
        state:
          enum:
          - New
          - Queued
          - Running
          - Succeeded
          - Failed
          - Canceling
          - Canceled
          type: string
        runBySchedule:
          type: boolean
      additionalProperties: false
    BackupScheduleDto:
      type: object
      properties:
        active:
          type: boolean
      additionalProperties: false
    BackupActiveRunDto:
      type: object
      properties:
        runId:
          type: integer
          format: int32
        date:
          type: string
          format: date-time
        duration:
          type: integer
          format: int32
        state:
          enum:
          - New
          - Queued
          - Running
          - Succeeded
          - Failed
          - Canceling
          - Canceled
          type: string
      additionalProperties: false
    BackupSnapshotLogDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/BackupSnapshotLogDto'
        hasMore:
          type: boolean
      additionalProperties: false
    BackupDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        scheduled:
          type: boolean
      additionalProperties: false
    BackupSnapshotLogDetailsDto:
      type: object
      properties:
        snapshotId:
          type: integer
          format: int32
        queueTime:
          type:
          - string
          - 'null'
          format: date-time
        startTime:
          type:
          - string
          - 'null'
          format: date-time
        endTime:
          type:
          - string
          - 'null'
          format: date-time
        state:
          enum:
          - New
          - Queued
          - Running
          - Succeeded
          - Failed
          - Canceling
          - Canceled
          type: string
        runBySchedule:
          type: boolean
        result:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Access_Token:
      type: apiKey
      description: Authorization header with the Skyvia access token.
      name: Authorization
      in: header
