openapi: 3.2.0
info:
  title: Skyvia public Endpoints API
  version: v1
security:
- Access Token: []
tags:
- name: Endpoints
paths:
  /v1/endpoints/types:
    get:
      tags:
      - Endpoints
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties:
                  OData:
                    type: integer
                    format: int32
                  Sql:
                    type: integer
                    format: int32
                additionalProperties: false
            application/json:
              schema:
                type: object
                properties:
                  OData:
                    type: integer
                    format: int32
                  Sql:
                    type: integer
                    format: int32
                additionalProperties: false
            text/json:
              schema:
                type: object
                properties:
                  OData:
                    type: integer
                    format: int32
                  Sql:
                    type: integer
                    format: int32
                additionalProperties: false
      summary: Get endpoints types
      x-summary-source: derived
      operationId: getV1EndpointsTypes
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints:
    get:
      tags:
      - Endpoints
      summary: Get endpoints
      parameters:
      - name: workspaceId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EndpointDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/EndpointDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdEndpoints
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints/{endpointId}:
    get:
      tags:
      - Endpoints
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: endpointId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EndpointDto'
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointDto'
            text/json:
              schema:
                $ref: '#/components/schemas/EndpointDto'
      summary: Get workspaces by workspace id endpoints by endpoint id
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdEndpointsByEndpointId
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints/{endpointId}/enable:
    post:
      tags:
      - Endpoints
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: endpointId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
      summary: Create workspaces by workspace id endpoints by endpoint id enable
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdEndpointsByEndpointIdEnable
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints/{endpointId}/disable:
    post:
      tags:
      - Endpoints
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: endpointId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
      summary: Create workspaces by workspace id endpoints by endpoint id disable
      x-summary-source: derived
      operationId: postV1WorkspacesByWorkspaceIdEndpointsByEndpointIdDisable
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints/{endpointId}/executions:
    get:
      tags:
      - Endpoints
      summary: Get requests log
      parameters:
      - name: workspaceId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: endpointId
        in: path
        description: ''
        required: true
        schema:
          type: integer
          format: int32
      - name: startDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: ''
        schema:
          type: string
          format: date-time
      - name: failed
        in: query
        description: ''
        schema:
          type: boolean
      - name: skip
        in: query
        description: Items to skip [0...]
        schema:
          type: integer
          format: int32
          default: 0
      - name: take
        in: query
        description: Items to take [1..200]
        schema:
          type: integer
          format: int32
          default: 20
      - name: sortOrder
        in: query
        description: 'To sort the available list of records in either ascending or descending order. Possible values: asc - ascending order, desc - descending order.The default value is ''asc''.'
        schema:
          type: string
          default: asc
      - name: sortBy
        in: query
        description: 'To sort the records based on the fields: date, executionId. The default value is ''date'''
        schema:
          type: string
          default: date
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDtoHasMorePagingDto'
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDtoHasMorePagingDto'
            text/json:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDtoHasMorePagingDto'
      operationId: getV1WorkspacesByWorkspaceIdEndpointsByEndpointIdExecutions
      x-operation-id-source: derived
  /v1/workspaces/{workspaceId}/endpoints/{endpointId}/executions/{recordId}:
    get:
      tags:
      - Endpoints
      parameters:
      - name: workspaceId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: endpointId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: recordId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDetailedDto'
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDetailedDto'
            text/json:
              schema:
                $ref: '#/components/schemas/EndpointRequestLogDetailedDto'
      summary: Get workspaces by workspace id endpoints by endpoint id executions by record id
      x-summary-source: derived
      operationId: getV1WorkspacesByWorkspaceIdEndpointsByEndpointIdExecutionsByRecordId
      x-operation-id-source: derived
components:
  schemas:
    EndpointRequestLogDetailedDto:
      type: object
      properties:
        date:
          type: string
          format: date-time
        url:
          type:
          - string
          - 'null'
        method:
          type:
          - string
          - 'null'
        remoteIP:
          type:
          - string
          - 'null'
        userAgent:
          type:
          - string
          - 'null'
        user:
          type:
          - string
          - 'null'
        error:
          type:
          - string
          - 'null'
        log:
          type:
          - array
          - 'null'
          items:
            type: string
        bytes:
          type: integer
          format: int32
        rows:
          type: integer
          format: int32
        pageToken:
          type:
          - string
          - 'null'
        external:
          type: boolean
      additionalProperties: false
    EndpointRequestLogDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EndpointRequestLogDto'
        hasMore:
          type: boolean
      additionalProperties: false
    EndpointRequestLogDto:
      type: object
      properties:
        executionId:
          type:
          - string
          - 'null'
        date:
          type: string
          format: date-time
        method:
          enum:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - TRACE
          type: string
        failed:
          type: boolean
        bytes:
          type: integer
          format: int32
        remoteIP:
          type:
          - string
          - 'null'
        url:
          type:
          - string
          - 'null'
      additionalProperties: false
    EndpointDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
        token:
          type:
          - string
          - 'null'
        active:
          type: boolean
        type:
          enum:
          - OData
          - Sql
          type: string
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
      additionalProperties: false
    EndpointDtoHasMorePagingDto:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/EndpointDto'
        hasMore:
          type: boolean
      additionalProperties: false
  securitySchemes:
    Access_Token:
      type: apiKey
      description: Authorization header with the Skyvia access token.
      name: Authorization
      in: header
